# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 17:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('id_no', models.CharField(max_length=10, null=True)),
                ('full_name', models.CharField(max_length=50, null=True)),
                ('branch', models.CharField(choices=[('CIV', 'Civil Engineering'), ('CHEM', 'Chemical Engineering'), ('CSE', 'Computer Science & Engineering'), ('ARCH', 'Architecture'), ('MECH', 'Mechanical Engineering'), ('META', 'Metallurgy'), ('MIN', 'Mining')], max_length=4)),
                ('enr_no', models.CharField(max_length=20, null=True)),
                ('cgpa', models.FloatField(max_length=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mrs', 'Mrs.'), ('Ms', 'Ms.'), ('Mr', 'Mr.')], max_length=4)),
                ('f_name', models.CharField(max_length=100)),
                ('m_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=4)),
                ('dob', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('company_type', models.CharField(max_length=100)),
                ('company_dept', models.CharField(choices=[('CIV', 'Civil Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('CHEM', 'Chemical Engineering'), ('CSE', 'Computer Science & Engineering'), ('ARCH', 'Architecture'), ('MECH', 'Mechanical Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('META', 'Metallurgy'), ('MIN', 'Mining')], max_length=4)),
                ('req_cgpa', models.FloatField(max_length=5, null=True)),
                ('last_date', models.DateField(null=True)),
                ('salary', models.CharField(max_length=100, null=True)),
                ('stipend', models.CharField(max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='applications',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Companies'),
        ),
        migrations.AddField(
            model_name='applications',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
