# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 06:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Companies'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=4),
        ),
        migrations.AlterField(
            model_name='applications',
            name='title',
            field=models.CharField(choices=[('Ms', 'Ms.'), ('Mrs', 'Mrs.'), ('Mr', 'Mr.')], max_length=4),
        ),
        migrations.AlterField(
            model_name='applications',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companies',
            name='company_dept',
            field=models.CharField(choices=[('CIV', 'Civil Engineering'), ('CHEM', 'Chemical Engineering'), ('MIN', 'Mining'), ('EEE', 'Electrical and Electronics Engineering'), ('CSE', 'Computer Science & Engineering'), ('META', 'Metallurgy'), ('MECH', 'Mechanical Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ARCH', 'Architecture')], max_length=4),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='branch',
            field=models.CharField(choices=[('CIV', 'Civil Engineering'), ('CHEM', 'Chemical Engineering'), ('MIN', 'Mining'), ('CSE', 'Computer Science & Engineering'), ('META', 'Metallurgy'), ('MECH', 'Mechanical Engineering'), ('ARCH', 'Architecture')], max_length=4),
        ),
    ]
