# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-12 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170210_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='company_dept',
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='applications',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=4),
        ),
        migrations.AlterField(
            model_name='applications',
            name='title',
            field=models.CharField(choices=[('Ms', 'Ms.'), ('Mr', 'Mr.'), ('Mrs', 'Mrs.')], max_length=4),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='branch',
            field=models.CharField(choices=[('CIV', 'Civil Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ARCH', 'Architecture'), ('CSE', 'Computer Science & Engineering'), ('MIN', 'Mining'), ('MECH', 'Mechanical Engineering'), ('CHEM', 'Chemical Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('META', 'Metallurgy')], max_length=4),
        ),
    ]
