# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170227_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=4),
        ),
        migrations.AlterField(
            model_name='applications',
            name='result',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='title',
            field=models.CharField(choices=[('Ms', 'Ms'), ('Mr', 'Mr'), ('Mrs', 'Mrs')], max_length=4),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='branch',
            field=models.CharField(choices=[('ECE', 'Electronics and Communication Engineering'), ('CIV', 'Civil Engineering'), ('CHEM', 'Chemical Engineering'), ('ARCH', 'Architecture'), ('META', 'Metallurgy'), ('CSE', 'Computer Science & Engineering'), ('MIN', 'Mining'), ('MECH', 'Mechanical Engineering'), ('EEE', 'Electrical and Electronics Engineering')], max_length=4),
        ),
    ]
