# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170302_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='dob',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=4),
        ),
        migrations.AlterField(
            model_name='applications',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs')], max_length=4),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='branch',
            field=models.CharField(choices=[('MIN', 'Mining'), ('ECE', 'Electronics and Communication Engineering'), ('CHEM', 'Chemical Engineering'), ('META', 'Metallurgy'), ('EEE', 'Electrical and Electronics Engineering'), ('MECH', 'Mechanical Engineering'), ('CIV', 'Civil Engineering'), ('ARCH', 'Architecture'), ('CSE', 'Computer Science & Engineering')], max_length=4),
        ),
    ]
