# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20170212_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=4),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='branch',
            field=models.CharField(choices=[('CIV', 'Civil Engineering'), ('META', 'Metallurgy'), ('ARCH', 'Architecture'), ('MECH', 'Mechanical Engineering'), ('MIN', 'Mining'), ('ECE', 'Electronics and Communication Engineering'), ('CHEM', 'Chemical Engineering'), ('CSE', 'Computer Science & Engineering'), ('EEE', 'Electrical and Electronics Engineering')], max_length=4),
        ),
    ]
