# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20170213_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=4),
        ),
        migrations.AlterField(
            model_name='applications',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Ms', 'Ms.')], max_length=4),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='branch',
            field=models.CharField(choices=[('META', 'Metallurgy'), ('EEE', 'Electrical and Electronics Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('CHEM', 'Chemical Engineering'), ('MIN', 'Mining'), ('MECH', 'Mechanical Engineering'), ('CIV', 'Civil Engineering'), ('CSE', 'Computer Science & Engineering'), ('ARCH', 'Architecture')], max_length=4),
        ),
    ]
